/**
 * Generates cms/scripts/site-content.json from the frontend fallback copy.
 *
 * The seed script runs inside the Strapi container, which has no TypeScript
 * toolchain, so it cannot import data/*.ts directly. Rather than keeping a
 * second hand-maintained copy of every string (which drifted before), the
 * copy is authored once in data/ and this script compiles it to JSON.
 *
 *   npm run seed:build
 *
 * Commit the generated JSON — the container reads it as-is.
 */
import { writeFileSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { dirname, resolve } from "node:path";

import { getHomeContent } from "../../data/homeContent.ts";
import { getAboutUsContent } from "../../data/aboutUsContent.ts";
import { getCataloguesContent } from "../../data/cataloguesContent.ts";

const LOCALES = ["es", "ca", "en", "fr"] as const;

const home = Object.fromEntries(
  LOCALES.map((locale) => {
    const c = getHomeContent(locale);
    return [
      locale,
      {
        hero_badge: c.hero_badge,
        hero_title: c.hero_title,
        hero_subtitle: c.hero_subtitle,
        hero_secondary_button: c.hero_secondary_button,
        hero_tag: c.hero_tag,
        search_placeholder: c.search_placeholder,
        search_button: c.search_button,
        search_suggestions: c.search_suggestions,
        stats: c.stats,
        plants_title: c.plants_title,
        plants_headline: c.plants_headline,
        plants_subtitle: c.plants_subtitle,
        plants_button: c.plants_button,
        how_title: c.how_title,
        how_steps: c.how_steps,
        catalogues_title: c.catalogues_title,
        catalogues_headline: c.catalogues_headline,
        catalogues_subtitle: c.catalogues_subtitle,
        catalogues_button: c.catalogues_button,
        contact_title: c.contact_title,
        contact_subtitle: c.contact_subtitle,
        contact_button: c.contact_button,
      },
    ];
  })
);

const aboutUs = Object.fromEntries(
  LOCALES.map((locale) => {
    const c = getAboutUsContent(locale);
    return [
      locale,
      {
        label: c.label,
        title: c.title,
        subtitle: c.subtitle,
        hero_button: c.hero_button,
        hero_secondary_button: c.hero_secondary_button,
        stats: c.stats,
        our_clients: c.our_clients,
        catalogues_title: c.catalogues_title,
        catalogues_headline: c.catalogues_headline,
        catalogues_subtitle: c.catalogues_subtitle,
        catalogues_button: c.catalogues_button,
      },
    ];
  })
);

const catalogue = Object.fromEntries(
  LOCALES.map((locale) => {
    const c = getCataloguesContent(locale);
    const home = getHomeContent(locale);
    return [
      locale,
      {
        main_title: c.main_title,
        main_subtitle: c.main_subtitle,
        main_button: c.main_button,
        section_title: c.section_title,
        section_subtitle: c.section_subtitle,
        contact_title: home.contact_title,
        contact_subtitle: home.contact_subtitle,
        contact_button: home.contact_button,
      },
    ];
  })
);

const out = resolve(
  dirname(fileURLToPath(import.meta.url)),
  "site-content.json"
);

writeFileSync(
  out,
  JSON.stringify(
    {
      _generated:
        "Generated by cms/scripts/build-seed-content.mts from data/*Content.ts — do not edit by hand.",
      locales: LOCALES,
      home,
      "about-us": aboutUs,
      catalogue,
    },
    null,
    2
  ) + "\n"
);

console.log(`wrote ${out}`);
